// Mapeo de símbolos a nombres de monedas FIAT
export const FIAT_NAMES: Record<string, string> = {
  AED: 'Dirham de Emiratos Árabes Unidos',
  AFN: 'Afgani afgano',
  ALL: 'Lek albanés',
  AMD: 'Dram armenio',
  ANG: 'Florín antillano neerlandés',
  AOA: 'Kwanza angoleño',
  ARS: 'Peso argentino',
  AUD: 'Dólar australiano',
  AWG: 'Florín arubeño',
  AZN: 'Manat azerbaiyano',
  BAM: 'Marco convertible de Bosnia-Herzegovina',
  BBD: 'Dólar barbadense',
  BDT: 'Taka bangladesí',
  BGN: 'Lev búlgaro',
  BHD: 'Dinar bareiní',
  BIF: 'Franco burundés',
  BMD: 'Dólar bermudeño',
  BND: 'Dólar de Brunéi',
  BOB: 'Boliviano',
  BRL: 'Real brasileño',
  BSD: 'Dólar bahameño',
  BTN: 'Ngultrum butanés',
  BWP: 'Pula botsuano',
  BYN: 'Rublo bielorruso',
  BZD: 'Dólar beliceño',
  CAD: 'Dólar canadiense',
  CDF: 'Franco congoleño',
  CHF: 'Franco suizo',
  CLP: 'Peso chileno',
  CNH: 'Yuan chino (extranjero)',
  CNY: 'Yuan chino',
  COP: 'Peso colombiano',
  CRC: 'Colón costarricense',
  CUP: 'Peso cubano',
  CVE: 'Escudo caboverdiano',
  CZK: 'Corona checa',
  DJF: 'Franco yibutiano',
  DKK: 'Corona danesa',
  DOP: 'Peso dominicano',
  DZD: 'Dinar argelino',
  EGP: 'Libra egipcia',
  ERN: 'Nakfa eritreo',
  ETB: 'Birr etíope',
  EUR: 'Euro',
  FJD: 'Dólar fiyiano',
  FKP: 'Libra malvinense',
  GBP: 'Libra esterlina',
  GEL: 'Lari georgiano',
  GGP: 'Libra de Guernsey',
  GHS: 'Cedi ghanés',
  GIP: 'Libra de Gibraltar',
  GMD: 'Dalasi gambiano',
  GNF: 'Franco guineano',
  GTQ: 'Quetzal guatemalteco',
  GYD: 'Dólar guyanés',
  HKD: 'Dólar de Hong Kong',
  HNL: 'Lempira hondureño',
  HTG: 'Gourde haitiano',
  HUF: 'Forinto húngaro',
  IDR: 'Rupia indonesia',
  ILS: 'Nuevo shéquel israelí',
  IMP: 'Libra de la Isla de Man',
  INR: 'Rupia india',
  IQD: 'Dinar iraquí',
  IRR: 'Rial iraní',
  ISK: 'Corona islandesa',
  JEP: 'Libra de Jersey',
  JMD: 'Dólar jamaiquino',
  JOD: 'Dinar jordano',
  JPY: 'Yen japonés',
  KES: 'Chelín keniata',
  KGS: 'Som kirguís',
  KHR: 'Riel camboyano',
  KMF: 'Franco comorense',
  KRW: 'Won surcoreano',
  KWD: 'Dinar kuwaití',
  KYD: 'Dólar caimán',
  KZT: 'Tenge kazajo',
  LAK: 'Kip laosiano',
  LBP: 'Libra libanesa',
  LKR: 'Rupia de Sri Lanka',
  LRD: 'Dólar liberiano',
  LSL: 'Loti lesotense',
  LYD: 'Dinar libio',
  MAD: 'Dirham marroquí',
  MDL: 'Leu moldavo',
  MGA: 'Ariary malgache',
  MKD: 'Denar macedonio',
  MMK: 'Kyat birmano',
  MNT: 'Tugrik mongol',
  MOP: 'Pataca de Macao',
  MRO: 'Ouguiya mauritano (antiguo)',
  MRU: 'Ouguiya mauritano',
  MUR: 'Rupia mauriciana',
  MVR: 'Rufiyaa maldiva',
  MWK: 'Kwacha malauí',
  MXN: 'Peso mexicano',
  MYR: 'Ringgit malasio',
  MZN: 'Metical mozambiqueño',
  NAD: 'Dólar namibio',
  NGN: 'Naira nigeriana',
  NIO: 'Córdoba nicaragüense',
  NOK: 'Corona noruega',
  NPR: 'Rupia nepalí',
  NZD: 'Dólar neozelandés',
  OMR: 'Rial omaní',
  PAB: 'Balboa panameño',
  PEN: 'Sol peruano',
  PGK: 'Kina papú',
  PHP: 'Peso filipino',
  PKR: 'Rupia pakistaní',
  PLN: 'Zloty polaco',
  PYG: 'Guaraní paraguayo',
  QAR: 'Riyal catarí',
  RON: 'Leu rumano',
  RSD: 'Dinar serbio',
  RUB: 'Rublo ruso',
  RWF: 'Franco ruandés',
  SAR: 'Riyal saudí',
  SBD: 'Dólar salomonense',
  SCR: 'Rupia seychellense',
  SDG: 'Libra sudanesa',
  SEK: 'Corona sueca',
  SGD: 'Dólar singapurense',
  SHP: 'Libra de Santa Elena',
  SLE: 'Leone sierraleonés',
  SOS: 'Chelín somalí',
  SRD: 'Dólar surinamés',
  SSP: 'Libra sursudanesa',
  STN: 'Dobra santotomense',
  SVC: 'Colón salvadoreño',
  SYP: 'Libra siria',
  SZL: 'Lilangeni suazi',
  THB: 'Baht tailandés',
  TJS: 'Somoni tayiko',
  TMT: 'Manat turcomano',
  TND: 'Dinar tunecino',
  TOP: "Pa'anga tongano",
  TRY: 'Lira turca',
  TTD: 'Dólar de Trinidad y Tobago',
  TWD: 'Nuevo dólar taiwanés',
  TZS: 'Chelín tanzano',
  UAH: 'Grivna ucraniana',
  UGX: 'Chelín ugandés',
  USD: 'Dólar estadounidense',
  UYU: 'Peso uruguayo',
  UZS: 'Som uzbeko',
  VES: 'Bolívar soberano venezolano',
  VND: 'Dong vietnamita',
  VUV: 'Vatu vanuatuense',
  WST: 'Tala samoano',
  XAF: 'Franco CFA de África Central',
  XAG: 'Plata (onza troy)',
  XAU: 'Oro (onza troy)',
  XCD: 'Dólar del Caribe Oriental',
  XCG: 'Unidad de cuenta Común',
  XOF: 'Franco CFA de África Occidental',
  XPD: 'Paladio (onza troy)',
  XPF: 'Franco CFP',
  XPT: 'Platino (onza troy)',
  YER: 'Rial yemení',
  ZAR: 'Rand sudafricano',
  ZMW: 'Kwacha zambiano',
  ZWG: 'Dólar zimbabuense',
};

export function getFiatName(symbol: string): string {
  return FIAT_NAMES[symbol] || symbol;
}
